"""Generate firmware/preview masks from bundled OFL font. Requires Pillow."""
from pathlib import Path
import base64, json, math
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
FONT = ROOT / 'assets/fonts/BarlowCondensed-Medium.ttf'
large = ImageFont.truetype(str(FONT), 800)
box = large.getbbox('0123456789')
scale_y = 150 / (box[3] - box[1])
scale_x = min(scale_y, 60 / max(large.getbbox(c)[2] - large.getbbox(c)[0] for c in '0123456789'))
glyphs = {}
for c in '0123456789:-':
    w = 24 if c == ':' else 64
    source = Image.new('L', (600, box[3] - box[1] + 16))
    b = large.getbbox(c)
    ImageDraw.Draw(source).text((8 - b[0], 8 - box[1]), c, font=large, fill=255)
    source = source.crop((0, 0, b[2] - b[0] + 16, source.height))
    source = source.resize((max(1, round(source.width * scale_x)), 154), Image.Resampling.LANCZOS)
    if c == ':' and source.width > w:
        source = source.resize((w - 4, 154), Image.Resampling.LANCZOS)
    mask = Image.new('L', (w, 154))
    mask.paste(source, ((w - source.width)//2, 0))
    if c == ':':
        smooth = Image.new('L', (w*4,154*4))
        draw = ImageDraw.Draw(smooth)
        for y in (56, 103):
            draw.ellipse((8*4,(y-4)*4,16*4-1,(y+4)*4-1),fill=255)
        mask = smooth.resize((w,154),Image.Resampling.LANCZOS)
    glyphs['large_' + c] = (mask, w)

small = ImageFont.truetype(str(FONT), 32 * 4)
top = small.getbbox('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789')[1]
for n in range(32, 127):
    c = chr(n)
    w = math.ceil(small.getlength(c) / 4) + 1
    mask = Image.new('L', (w * 4, 36 * 4))
    ImageDraw.Draw(mask).text((0, -top), c, font=small, fill=255)
    mask = mask.resize((w, 36), Image.Resampling.LANCZOS)
    glyphs['small_' + c] = (mask, w)

data, records, preview = [], [], {}
for key, (mask, advance) in glyphs.items():
    values = bytes(round(v * 15 / 255) for v in mask.tobytes())
    records.append((len(data), mask.width, mask.height, advance))
    data.extend(values)
    preview[key] = dict(w=mask.width, h=mask.height, advance=advance, data=base64.b64encode(values).decode())
header = '// Generated by tools/generate_font.py. Font license: assets/fonts/OFL.txt\n#pragma once\n'
header += 'struct ClockGlyph { uint32_t offset; uint16_t w, h, advance; };\n'
header += 'static const uint8_t CLOCK_ALPHA[] PROGMEM = {\n'
header += '\n'.join(','.join(map(str, data[i:i+64])) + ',' for i in range(0,len(data),64)) + '\n};\n'
header += 'static const ClockGlyph CLOCK_GLYPHS[] = {\n' + '\n'.join('{' + ','.join(map(str,r)) + '},' for r in records) + '\n};\n'
(ROOT/'src/clock_font.h').write_text(header)
(ROOT/'assets/font-data.js').write_text('const CLOCK_FONT = ' + json.dumps(preview,separators=(',',':')) + ';\n')

# Native firmware-scale contact sheet, using the same quantized masks.
sheet = Image.new('RGB', (640, 480), '#17191b')
for text, pos in [('9:41',(0,0)),('10:58',(320,0)),('11:59',(0,240)),('12:00',(320,240))]:
    panel = Image.new('RGB', (320,240))
    width = sum(glyphs['large_'+c][1] for c in text) + 6*(len(text)-1)
    x = (320-width)//2
    for c in text:
        mask, advance = glyphs['large_'+c]
        mask = mask.point(lambda v: round(v*15/255)*17)
        panel.paste((245,241,232),(x,18),mask)
        x += advance+6
    for label, x in [('Sun, Sep 6',12),('PM',270)]:
        for c in label:
            mask, advance = glyphs['small_'+c]
            panel.paste((214,215,211),(x,200),mask)
            x += advance
    sheet.paste(panel,pos)
(ROOT/'artifacts').mkdir(exist_ok=True)
sheet.save(ROOT/'artifacts/type-preview.png')
print(f'Generated {len(records)} glyphs, {len(data):,} bytes of flash masks.')
